name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  test-linux:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - run: zig build
